### ISSUE TITLE
consumerKey not to be disclosed

### ISSUE THREAD

**Issue by ArturZurawski** [baarde/cert-manager-webhook-ovh#21]
`consumerKey` is advised by OVH not to be disclosed. Is it safe to store it in plaintext? 
> a secret “consumer key“, not to be disclosed, called CK. For example:
https://support.us.ovhcloud.com/hc/en-us/articles/360018130839-First-Steps-with-the-OVHcloud-API

Maybe it could be referenced as same as `applicationKey`?

**Comment by aureq** [comment]
This issue has been solved where `applicaiotnKey`, `applicationSecret` and `consumerKey` are stored in a secret.

Head to https://github.com/aureq/cert-manager-webhook-ovh for more details.
